# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Check with Svelte, build with pnpm, deploy to gh-pages
on:
  push:
    branches: ["**"]
jobs:
  check_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true
      - name: Check with Svelte
        run: pnpm run check
      - name: Build with pnpm
        run: pnpm run build
      - name: Deploy to gh-pages
        run: pnpm run deploy
