name: Lint with Prettier, check with Svelte, and build with pnpm
on:
  push:
    branches: ["**"]
jobs:
  lint_check_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true
      - name: Lint with Prettier
        run: pnpm run lint
      - name: Check with Svelte
        run: pnpm run check
      - name: Build with pnpm
        run: pnpm run build
